apiVersion: v2
name: deepep-internode-test
description: DeepEP multi-node inter-node communication test
type: application
version: 0.1.0
appVersion: "1.2.1"
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.svg
keywords:
  - rdma
  - gpu
  - deepep
  - moe
  - infiniband
  - roce
  - nccl
  - nvshmem
  - distributed
  - testing
sources:
  - https://github.com/llm-d-incubation/llmd-cluster-wizard
  - https://github.com/deepseek-ai/DeepEP
maintainers:
  - name: llm-d-incubation
    email: noreply@github.com
