apiVersion: v1
kind: Service
metadata:
  name: pplx-kernels-master-{{ .Values.testId }}
  namespace: {{ .Values.namespace }}
  labels:
    app: pplx-kernels-test
    role: master
    test-id: {{ .Values.testId | quote }}
    {{- if .Values.topology }}
    platform: {{ .Values.topology.platform }}
    {{- end }}
spec:
  clusterIP: None
  selector:
    app: pplx-kernels-test
    role: master
    test-id: {{ .Values.testId | quote }}
  ports:
  - port: {{ .Values.distributed.masterPort }}
    name: dist
